# thread support not complete on wasi
# see https://github.com/rust-lang/rust/issues/77839
# [target.wasm32-wasi]
# rustflags = [
#   "-Ctarget-feature=-crt-static,+atomics,+bulk-memory",
#   "-LE:/develop/automa/chainblocks/build-wasm-rel",
#   # "-Clink-arg=--shared-memory",
#   # "-Clink-arg=--max-memory=1073741824",
#   # "-Clink-arg=--import-memory",
#   # "-Clink-arg=--export=__wasm_init_memory",
#   # "-Clink-arg=--export=__wasm_init_tls",
#   # "-Clink-arg=--export=__tls_size",
#   # "-Clink-arg=--export=__tls_align",
#   # "-Clink-arg=--export=__tls_base",
#   ]
