buildAndRun:win:  
  script:
    - cd src/nim
    - nimble install --depsOnly -y
    - nim cpp --newruntime -r -f chainblocks.nim
    - nim cpp -r -f chainblocks.nim
    - cd blocks/external/py
    - nim cpp -f py.nim
    - nim cpp -f pytest.nim
  tags:
    - WIN, NIM, BOOST, MINGW
