buildAndRun:win:  
  script:
    - cd src/nim
    - nimble install --depsOnly -y
    - nim cpp --newruntime -r chainblocks.nim
    - nim cpp -r chainblocks.nim
    - cd blocks/external/py
    - nim cpp py.nim
    - nim cpp pytest.nim
  tags:
    - WIN, NIM, BOOST, MINGW
