buildAndRun:win:  
  script:
    - cd src/nim
    - nimble install --depsOnly -y
    - nim cpp --newruntime -r -f chainblocks.nim
    - nim cpp -r -f chainblocks.nim
    - cd blocks/external/py
    - nim cpp -f py.nim
    - 'call C:\ProgramData\Miniconda3\Scripts\activate.bat C:\ProgramData\Miniconda3'
    - nim cpp -f -r pytest.nim
  tags:
    - WIN, NIM, BOOST, MINGW
