buildAndRun:win:  
  script:
    - cd src/nim
    - nimble install --depsOnly -y
    - nim cpp --newruntime -r -f chainblocks.nim
    - nim cpp -r -f chainblocks.nim
    - cd blocks/external/py
    - nim cpp -f py.nim
    - powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'C:\ProgramData\Miniconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\ProgramData\Miniconda3' "
    - nim cpp -f -r pytest.nim
    # Finally install it so to let other repo use this build internally in the CI machine (this is a hack btw, works just cos 1 builder is present and we need to fix it soon)
    - nimble install -y
  tags:
    - WIN, NIM, BOOST, MINGW
