buildAndRun:win:debug:
  script:
    - $currentDir = Get-Location
    - $nimbleDir = "$currentDir/nimbledir"
    - cd src/nim
    - nimble install --depsOnly --nimbleDir:$nimbleDir -y
    - cd $currentDir
    - mkdir build
    - cd build
    - cmake -G Ninja -DNIMBLE_PATH="$nimbleDir/pkgs" -DCMAKE_BUILD_TYPE=Debug ..
    - ninja cbl
    - cbl ../src/tests/general.clj
  tags:
    - WIN, NIM, BOOST, MINGW

buildAndRun:win:release:  
  script:
    - $currentDir = Get-Location
    - $nimbleDir = "$currentDir/nimbledir"
    - cd src/nim
    - nimble install --depsOnly --nimbleDir:$nimbleDir -y
    - cd $currentDir
    - mkdir build
    - cd build
    - cmake -G Ninja -DNIMBLE_PATH="$nimbleDir/pkgs" -DCMAKE_BUILD_TYPE=Release ..
    - ninja cbl
    - cbl ../src/tests/general.clj
  tags:
    - WIN, NIM, BOOST, MINGW

# buildAndRun:linux:debug:
#   script:
#     # clean up docker - make sure we got space
#     - docker rm $(docker ps -q -f status=exited) || true
#     - docker volume rm $(docker volume ls -qf dangling=true) || true
#     - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || true
#     # build docker image
#     - docker build -f docker/linux/Dockerfile -t chainblocks-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg JOB_ID=$CI_JOB_ID .
#     # gcc
#     - docker run --rm -t -u`id -u`:`id -g` chainblocks-test bash -c "cd src/nim && nimble install --depsOnly -y && nim cpp --newruntime -d:useMalloc -d:blocksTesting -r -f chainblocks.nim"
#   tags:
#     - LINUX, DOCKER

# buildAndRun:linux:release:
#   script:
#     # clean up docker - make sure we got space
#     - docker rm $(docker ps -q -f status=exited) || true
#     - docker volume rm $(docker volume ls -qf dangling=true) || true
#     - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || true
#     # build docker image
#     - docker build -f docker/linux/Dockerfile -t chainblocks-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg JOB_ID=$CI_JOB_ID .
#     # gcc
#     - docker run --rm -t -u`id -u`:`id -g` chainblocks-test bash -c "cd src/nim && nimble install --depsOnly -y && nim cpp -d:release -d:danger --newruntime -d:useMalloc -d:blocksTesting -r -f chainblocks.nim && clang++ -c ../core/runtime.cpp"
#   tags:
#     - LINUX, DOCKER
