buildAndRun:win:debug:
  script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
    - ninja cbl
    - .\cbl.exe ../src/tests/general.clj
    - .\cbl.exe ../src/tests/loader.clj
    - .\cbl.exe ../src/tests/variables.clj
    - .\cbl.exe ../src/tests/subchains.clj
  tags:
    - WIN, NIM, BOOST, MINGW

buildAndRun:win:release:  
  script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
    - ninja cbl
    - .\cbl.exe ../src/tests/general.clj
    - .\cbl.exe ../src/tests/loader.clj
    - .\cbl.exe ../src/tests/variables.clj
    - .\cbl.exe ../src/tests/subchains.clj
  tags:
    - WIN, BOOST, MINGW

buildAndRun:linux:debug:
  script:
    # clean up docker - make sure we got space
    - docker rm $(docker ps -q -f status=exited) || true
    - docker volume rm $(docker volume ls -qf dangling=true) || true
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || true
    # build docker image
    - docker build -f docker/linux/Dockerfile -t chainblocks-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg JOB_ID=$CI_JOB_ID .
    # run
    # to run with gdb for diagnostics gdb -return-child-result -ex 'catch throw' -ex 'break abort' -ex run -ex bt -batch --args
    - docker run --rm -t --cap-add=SYS_PTRACE -u`id -u`:`id -g` chainblocks-test bash -c "mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug .. && ninja cbl && ./cbl ../src/tests/general.clj && ./cbl ../src/tests/variables.clj"
  tags:
    - LINUX, DOCKER

buildAndRun:linux:release:
  script:
    # clean up docker - make sure we got space
    - docker rm $(docker ps -q -f status=exited) || true
    - docker volume rm $(docker volume ls -qf dangling=true) || true
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || true
    # build docker image
    - docker build -f docker/linux/Dockerfile -t chainblocks-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg JOB_ID=$CI_JOB_ID .
    # run
    - docker run --rm -t --cap-add=SYS_PTRACE -u`id -u`:`id -g` chainblocks-test bash -c "mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. && ninja cbl && ./cbl ../src/tests/general.clj && ./cbl ../src/tests/variables.clj && clang++ -std=c++17 -c -I../src/core ../src/core/runtime.cpp"
  tags:
    - LINUX, DOCKER
