[package]
name = "chainblocks"
description = "rust bindings and utility in order to use chainblocks"
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
approx = "0.4.0"
lazy_static = "1.4.0"
compile-time-crc32 = "0.1.2"
tiny-keccak = { version = "2.0.2", features = ["keccak"], optional = true }
libsecp256k1 = { version = "0.3.5", optional = true }
hex = { version = "0.4.2", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
dlopen = { version = "0.1.8", optional = true }
reqwest = { version = "0.10", features = ["blocking"], optional = true }

[dev-dependencies]
ctor = "0.1.16"

[build-dependencies]
bindgen = { version = "0.55.1", optional = true }

[features]
default = []
dummy = []
blocks = ["reqwest", "tiny-keccak", "libsecp256k1", "hex"]
dllblock = ["dlopen"]
run_bindgen = ["bindgen"]