name: Build (Linux docker)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  #
  # Build chainblocks and publish docker image
  #
  Linux-docker:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chainblocks
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Build and upload to hub devel image
        uses: chainblocks/Publish-Docker-Github-Action@master
        with:
          name: chainblocks/devenv
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/linux/Dockerfile
          tags: "latest"
      - name: Build and Test
        run: |
          docker run --name chainblocks -t --cap-add=SYS_PTRACE chainblocks/devenv:latest bash -c "./bootstrap && mkdir build && cd build && cmake -G Ninja -DFORCE_CORE2=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && ninja cbl && ./cbl ../src/tests/general.edn && ./cbl ../src/tests/variables.clj && ./cbl ../src/tests/linalg.clj && ./cbl ../src/tests/channels.clj"
          mkdir build
          docker cp chainblocks:/home/chainblocks/repo/build/cbl ./build/cbl
      - name: Build and upload to hub runtime image
        uses: chainblocks/Publish-Docker-Github-Action@master
        if: ${{ github.ref == 'refs/heads/devel' && github.event_name == 'push' }}
        with:
          name: chainblocks/cbl
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/linux/Dockerfile-runtime
          tags: "latest"
