name: Build (macOS)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: build in release or debug
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      runtime-tests:
        description: Run the runtime tests?
        required: true
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      runtime-tests:
        required: true
        default: false
        type: boolean

jobs:
  #
  # Build chainblocks for macOS
  #
  macOS:
    name: macOS (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: macos-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"
      - name: Checkout chainblocks
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          brew install cmake ninja clang-format
          ./bootstrap
          rustup toolchain install nightly
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DSKIP_HEAVY_INLINE=1 -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }} ..
          ninja cbl
      - name: Test runtime (Debug)
        if: ${{ steps.setup.outputs.runtime-tests && steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          ninja test_runtime
          ./test_runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cbl-macos ${{ steps.setup.outputs.build-type }}
          path: build/cbl
          if-no-files-found: error
