name: Build (Windows)

on:
  workflow_dispatch:
    inputs:
      bitness:
        description: Build for 32-bit or 64-bit?
        required: true
        default: 64bits
        type: choice
        options:
          - 32bits
          - 64bits
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      runtime-tests:
        description: Run the runtime tests (Debug only)?
        required: false
        default: false
        type: boolean
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      bitness:
        required: true
        default: 64bits
        type: string
      build-type:
        required: true
        default: Debug
        type: string
      runtime-tests:
        required: false
        default: false
        type: boolean
      run-tests:
        required: false
        default: false
        type: boolean

jobs:
  #
  # Build chainblocks for Windows
  #
  Windows:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }}, ${{ github.event.inputs.bitness || inputs.bitness }})
    runs-on: windows-2019
    outputs:
      run-tests: ${{ steps.setup.outputs.run-tests }}
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "::set-output name=bitness::${{ github.event.inputs.bitness || inputs.bitness }}"
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"
          echo "::set-output name=run-tests::${{ github.event.inputs.run-tests || inputs.run-tests }}"
          echo "::set-output name=runtime-tests::${{ github.event.inputs.runtime-tests || inputs.runtime-tests }}"

          if [ "${{ github.event.inputs.bitness || inputs.bitness }}" == "64bits" ]
          then
            echo "::set-output name=msystem::MINGW64"
            echo "::set-output name=arch::x86_64"
            echo "::set-output name=artifact::cbl-win64"
          else
            echo "::set-output name=msystem::MINGW32"
            echo "::set-output name=arch::i686"
            echo "::set-output name=artifact::cbl-win32"
          fi
      - name: Checkout chainblocks
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up rust
        env:
          RUSTUP_USE_CURL: 1
        run: |
          rustup toolchain install nightly
          rustup +nightly target add ${{ steps.setup.outputs.arch }}-pc-windows-gnu
          rustup default nightly-${{ steps.setup.outputs.arch }}-pc-windows-gnu
      - name: Set up rust (32-bits)
        if: ${{ steps.setup.outputs.bitness == '32bits' }}
        env:
          RUSTUP_USE_CURL: 1
        shell: bash
        run: |
          # Native libClang required for rust bindgen
          # choco exit with code 1 after successful install
          choco install -y --force llvm || exit 0
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\lib" >> $GITHUB_ENV
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ steps.setup.outputs.msystem }}
          release: false
          path-type: inherit
          install: >-
            base-devel
            mingw-w64-${{ steps.setup.outputs.arch }}-toolchain
            mingw-w64-${{ steps.setup.outputs.arch }}-cmake
            mingw-w64-${{ steps.setup.outputs.arch }}-ninja
            mingw-w64-${{ steps.setup.outputs.arch }}-clang
            mingw-w64-${{ steps.setup.outputs.arch }}-lld
            wget
      - name: Build libtrace (64bits)
        if: ${{ steps.setup.outputs.bitness == '64bits' }}
        shell: msys2 {0}
        run: |
          cd deps/libbacktrace
          mkdir build
          ./configure --prefix=`pwd`/build
          make && make install
      - name: Build
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          ./bootstrap
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }} -DUSE_LIBBACKTRACE=${{ steps.setup.outputs.bitness == '64bits' }} ..
          ninja cbl
      - name: Test runtime (Debug)
        if: ${{ steps.setup.outputs.runtime-tests == 'true' && steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd build
          ninja test_runtime
          ./test_runtime
      - name: Test graphics (Debug)
        # NOTE: Graphics backend doesn't run on 32bits
        if: ${{ steps.setup.outputs.runtime-tests == 'true' && steps.setup.outputs.build-type == 'Debug' && steps.setup.outputs.bitness == '64bits' }}
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd build
          ninja test_gfx
          GFX_TEST_PLATFORM_ID="github-windows" ./test_gfx
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.artifact }} ${{ steps.setup.outputs.build-type }}
          path: build/cbl.exe
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ steps.setup.outputs.artifact }} rejected test data
          path: src/gfx/tests/data/github-windows/rejected
          if-no-files-found: warn

  #
  # Test chainblocks for Windows
  #
  Windows-test:
    if: ${{ needs.Windows.outputs.run-tests == 'true' }}
    needs: Windows
    name: Test
    runs-on: windows-2019
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "::set-output name=bitness::${{ github.event.inputs.bitness || inputs.bitness }}"
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"

          if [ "${{ github.event.inputs.bitness || inputs.bitness }}" == "64bits" ]
          then
            echo "::set-output name=msystem::MINGW64"
            echo "::set-output name=arch::x86_64"
            echo "::set-output name=artifact::cbl-win64"
          else
            echo "::set-output name=msystem::MINGW32"
            echo "::set-output name=arch::i686"
            echo "::set-output name=artifact::cbl-win32"
          fi
      - name: Change git line endings
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.setup.outputs.artifact }} ${{ steps.setup.outputs.build-type }}
          path: build
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ steps.setup.outputs.msystem }}
          release: false
          path-type: inherit
      - name: Test
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd build
          echo "Running test: general"
          ./cbl ../src/tests/general.edn
          echo "Running test: variables"
          ./cbl ../src/tests/variables.clj
          echo "Running test: linalg"
          ./cbl ../src/tests/linalg.clj
          echo "Running test: loader"
          ./cbl ../src/tests/loader.clj
          echo "Running test: network"
          ./cbl ../src/tests/network.clj
          echo "Running test: struct"
          ./cbl ../src/tests/struct.clj
          echo "Running test: flows"
          ./cbl ../src/tests/flows.clj
          echo "Running test: kdtree"
          ./cbl ../src/tests/kdtree.clj
          echo "Running test: channels"
          ./cbl ../src/tests/channels.clj
          echo "Running test: http"
          ./cbl ../src/tests/http.clj
          echo "Running test: brotli"
          ./cbl ../src/tests/brotli.clj
          echo "Running test: snappy"
          ./cbl ../src/tests/snappy.clj
          # echo "Running test: ws"
          # ./cbl ../src/tests/ws.clj
          echo "Running test: bigint"
          ./cbl ../src/tests/bigint.clj
          echo "Running test: wasm"
          ./cbl ../src/tests/wasm.clj
          echo "Running test: eth"
          ./cbl ../src/tests/eth.edn
          echo "Running test: crypto"
          ./cbl ../src/tests/crypto.edn
      - name: Graphics Test (64bits)
        # NOTE: Graphics backend doesn't run on 32bits
        if: ${{ steps.setup.outputs.bitness == '64bits' }}
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd build
          echo "Running test: gfx_window"
          ./cbl ../src/tests/gfx_window.edn
          echo "Running test: gfx_cube"
          ./cbl ../src/tests/gfx_cube.edn
          echo "Running test: gfx_materials"
          ./cbl ../src/tests/gfx_materials.edn
          echo "Running test: imgui_demo"
          ./cbl ../src/tests/imgui_demo.edn
      - name: Test (64bits)
        if: ${{ steps.setup.outputs.bitness == '64bits' }}
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd build
          echo "Running test: genetic"
          ./cbl ../src/tests/genetic.clj
          echo "Running test: time"
          ./cbl ../src/tests/time.edn
          echo "Running test: subchains"
          ./cbl ../src/tests/subchains.clj
