name: Documentation

on:
  workflow_dispatch:

jobs:

  #
  # Build chainblocks x64 for Windows
  #
  Windows-64bits:
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: ["Release"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up rust
        env:
          RUSTUP_USE_CURL: 1
        run: rustup update
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: false
          path-type: inherit
      - name: Build
        env:
          RUST_BACKTRACE: 1
        run: |
          msys2 ./build-win.sh ${{ matrix.build-type }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cbl-win64 ${{ matrix.build-type }}
          path: build/cbl.exe
          if-no-files-found: error

  #
  # Run blocks documentation samples
  #
  docs-samples:
    needs: Windows-64bits
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cbl-win64 Release
          path: docs\samples
      - name: Run samples
        shell: pwsh
        run: |
          cd docs\samples
          dir blocks -recurse -include *.edn | %{
            echo ("Running sample " + ($_ | Resolve-Path -Relative))
            .\cbl.exe .\run_sample.edn --file $_.FullName
          }

  #
  # Generate blocks documentation (markdown)
  #
  docs-markdown:
    needs: Windows-64bits
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cbl-win64 Release
      - name: Generate markdown
        shell: bash
        run: ./cbl.exe src/tests/infos_docs.edn
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-markdown
          path: |
            docs/docs/blocks/**/*.md
            !docs/docs/blocks/index.md
          if-no-files-found: error

  #
  # Build documentation website
  #
  docs-website-build:
    needs: docs-markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-markdown
          path: docs/docs/blocks
      - name: Build website
        run: |
          cd docs
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-website
          path: |
            docs/site/
          if-no-files-found: error

  #
  # Publish documentation website to IPFS
  #
  docs-website-publish:
    if: ${{ github.event_name != 'pull_request' }}
    needs: docs-website-build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-website
          path: docs/site
      - name: Publish to IPFS
        uses: chainblocks/ipfs-action@master
        with:
          path: docs/site/
          service: infura
          port: 5001
          protocol: https
