name: CI

on:
  push:
    branches:
      - devel
  pull_request:
  workflow_dispatch:

jobs:
  # cancel-previous-workflows:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: chainblocks/cancel-workflow-action@0.7.0
  #       with:
  #         access_token: ${{ secrets.TOKEN }}

  #
  # Build chainblocks for emscripten
  #
  wasm32-emscripten-st:
    uses: ./.github/workflows/build-wasm.yml
    secrets: inherit
    with:
      threading: st
      run-tests: true
  wasm32-emscripten-mt:
    uses: ./.github/workflows/build-wasm.yml
    secrets: inherit
    with:
      threading: mt
      run-tests: true

  #
  # Build chainblocks for linux
  #
  Linux-Debug:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Debug
      run-tests: true
      run-extra-tests: true
  Linux-Release:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Release
      run-tests: true

  #
  # Build chainblocks and publish docker image
  #
  Linux-docker:
    uses: ./.github/workflows/build-linux-docker.yml
    secrets: inherit

  # Linux-docker-VK:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #     name: Checkout
  #   - name: Fetch submodules
  #     run: |
  #       git submodule update --init --recursive
  #   - uses: chainblocks/Publish-Docker-Github-Action@master
  #     name: Build and upload to hub devel image
  #     with:
  #       name: chainblocks/devenv
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       dockerfile: docker/linux/Dockerfile
  #       tags: "latest"
  #   - name: Build and Test
  #     run: |
  #       docker run --name chainblocks -t --cap-add=SYS_PTRACE chainblocks/devenv:latest bash -c "mkdir build && cd build && cmake -G Ninja -DFORCE_USE_VULKAN=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && ninja cbl && ./cbl ../src/tests/general.edn && ./cbl ../src/tests/variables.clj && ./cbl ../src/tests/linalg.clj && ./cbl ../src/tests/channels.clj"
  #       mkdir build
  #       docker cp chainblocks:/home/chainblocks/repo/build/cbl ./build/cbl
  #   - uses: chainblocks/Publish-Docker-Github-Action@master
  #     if: ${{ github.ref == 'refs/heads/devel' && github.event_name != 'pull_request' }}
  #     name: Build and upload to hub runtime image
  #     with:
  #       name: chainblocks/cbl
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       dockerfile: docker/linux/Dockerfile-runtime
  #       tags: "latest-vulkan"

  #
  # Build chainblocks and run valgrind on Linux
  #
  Linux-valgrind:
    uses: ./.github/workflows/build-linux-valgrind.yml
    secrets: inherit

  #
  # Build chainblocks for Windows
  #
  Windows-64bits-Debug:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      bitness: 64bits
      build-type: Debug
      runtime-tests: true
      run-tests: true
  Windows-64bits-Release:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      bitness: 64bits
      build-type: Release
      run-tests: true
  Windows-32bits-Debug:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      bitness: 32bits
      build-type: Debug
      runtime-tests: true
      run-tests: true
  Windows-32bits-Release:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      bitness: 32bits
      build-type: Release
      run-tests: true

  #
  # Build the documentation
  #
  docs:
    needs: [Windows-64bits-Debug, Windows-64bits-Release]
    uses: ./.github/workflows/build-doc.yml
    secrets: inherit
    with:
      publish: ${{ github.ref == 'refs/heads/devel' && github.event_name == 'push' }}

  #
  # Build chainblocks for macOS
  #
  macOS-Debug:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      build-type: Debug
      runtime-tests: true
      run-tests: true
  macOS-Release:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      build-type: Release
      runtime-tests: true
      run-tests: true

  #
  # Build chainblocks for iOS
  #
  iOS:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
